#!/usr/bin/env python

import pandas as pd
import datetime as dt

def get_companies():
    data = pd.read_csv('../Data/Raw/Companies.csv')
    list_of_companies = list(data['company_name'])
    #print(list_of_companies)
    return list_of_companies

def get_paired_company_jobsite():
    jobsite_data = pd.read_csv('../Data/Raw/Jobsite.csv')
    list_of_companies = get_companies()
    jobsites = []
    for company in list_of_companies:
        jobsites_at_company = jobsite_data.loc[jobsite_data['company_name']==company]['jobsite_name']
        jobsites.append(jobsites_at_company.to_list())
        #print(jobsites_at_company.to_list())
    return (list_of_companies, jobsites)

def ticket_revenue(ticket_number):
    ''' Returns the revenue generated by a specific ticket.'''
    ticket_data = pd.read_csv('../Data/Raw/Tickets.csv')
    # filter data for specific ticket number
    ticket_data = ticket_data.loc[ticket_data['external_id']==ticket_number]
    type_of_material = str(ticket_data['material_type'][0])
    material_weight = float(ticket_data['net_weight'][0])
    rate = float(ticket_data['rate'][0])
    revenue = round(material_weight * rate, 3)
    return revenue

def days_tickets(company, desired_date):
    '''returns a list of tickets for a specific company and day'''
    data = pd.read_csv('../Data/Raw/Tickets.csv')
    # Make date column datetime objects
    data['date'] = pd.to_datetime(data['date'],yearfirst=True, format='%Y-%m-%d').dt.date
    desired_date = list(map(int, desired_date.split(sep='-')))
    desired_date = dt.date(desired_date[0], desired_date[1], desired_date[2])
    print(desired_date)
    return_data = data.loc[data['date'] == desired_date]
    print(return_data)

def main():
    days_tickets('Big Inc', '2021-1-2')

if __name__=='__main__':
    main()